-- create new schema

CREATE DATABASE ASSIGNMENT_SCHEMA;
USE ASSIGNMENT_SCHEMA;

CREATE TABLE MOVIE_RATINGS
(
M_NAME VARCHAR(255),
M_R VARCHAR(255));

INSERT INTO MOVIE_RATINGS
VALUES
('ABC','4'),
('XYZ','5'),
('PQR','7');

SELECT * FROM MOVIE_RATINGS; 

ALTER TABLE MOVIE_RATINGS MODIFY COLUMN M_R VARCHAR(10) CHECK(M_R>0);

INSERT INTO MOVIE_RATINGS
VALUES
('ABC',0),
('XYZ',-2);

SELECT * FROM MOVIE_RATINGS; 


